name: OrangeFox
on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'OrangeFox - branch'
        required: true
        default: '12.1'
        type: choice
        options:
        - '14.1'
        - '12.1'
        - '11.0'
      DT:
        description: 'Device tree - repo'
        required: true
        default: 'https://github.com/cachiusa/orangefox_device_xiaomi_veux.git'
      DT_BRANCH:
        description: 'Device tree - branch'
        required: true
        default: 'fox_12.1'
      DT_PATH:
        description: 'Device tree - path'
        required: true
        default: 'device/xiaomi/veux'
      DT_NAME:
        description: 'Device - name'
        required: true
        default: 'veux'
      USE_CCACHE:
        description: 'Use ccache'
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest #22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v6
              
#    - name: Clean-up
#      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap on
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24
      
    - name: apt install & repo install
      run: |
        echo "Installing..."
        sudo apt-get update
        sudo apt-get install \
        git-core gnupg flex bison build-essential zip curl zlib1g-dev \
        libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev \
        libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

        echo "Installing repo"
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O \
        -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+rx /usr/local/bin/repo


    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      if: github.event.inputs.USE_CCACHE == 'true'
      with:
        max-size: "5G"
      
    - name: repo sync
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox; cd ${GITHUB_WORKSPACE}/OrangeFox
        echo "OFOX_TOP=${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}" >> $GITHUB_ENV
        git config --global user.name "github"
        git config --global user.email "nobody@github.com"
        git clone https://gitlab.com/OrangeFox/sync.git -b master; cd sync
        ./orangefox_sync.sh \
          --branch ${{ github.event.inputs.MANIFEST_BRANCH }} \
          --path ${{ env.OFOX_TOP }}


    - name: Show free space
      run: df -h

    - name: Get device tree
      run: |
        cd ${{ env.OFOX_TOP }}
        git clone \
            ${{ github.event.inputs.DT }} \
            -b ${{ github.event.inputs.DT_BRANCH }} \
            ./${{ github.event.inputs.DT_PATH }} ; cd ${{ github.event.inputs.DT_PATH }}
        echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

        if [[ ${{ github.event.inputs.DT_NAME }} = "veux" ]]; then
          cd -; set +e; source build/envsetup.sh
          sed -i '$ a CONFIG_KSU=y' kernel/xiaomi/sm6375/arch/arm64/configs/veux_defconfig
        fi

    - name: Build
      run: |
        set +e
        cd ${{ env.OFOX_TOP }}
        
        if [[ ${{ github.event.inputs.USE_CCACHE }} = true ]]; then
          export USE_CCACHE=1
          export CCACHE_EXEC=/usr/bin/ccache
          # hack: allow ccache dir inside of $ANDROID_BUILD_TOP
          sed -i 's/return sandboxConfig\.working/return false/g' build/soong/ui/build/sandbox_linux.go
        fi

        source build/envsetup.sh
        lunch twrp_${{ github.event.inputs.DT_NAME }}-eng && mka adbd vendorbootimage
        
        if [[ ${{ github.event.inputs.DT_NAME }} = "veux" ]]; then
          export TWRP_BUILD_BOOT_IMAGE=1
          source build/envsetup.sh
          lunch twrp_veux-eng && mka adbd bootimage
        fi

    - name: Post-build
      run: |
        if [[ ${{ github.event.inputs.DT_NAME }} = "veux" ]]; then
            cd ${{ env.OFOX_TOP }}; mkdir tempo; cd tempo
            mgb=${{ env.OFOX_TOP }}/vendor/recovery/tools/magiskboot

            for i in $(find ../out/target/product/veux -name "OrangeFox-*.img"); do
                $mgb unpack $i
                if [[ $i == *"vendor_boot"* ]]; then
                    mv ramdisk.cpio vendor_boot.cpio
                else
                    mv ramdisk.cpio boot.cpio
                fi
                $mgb cleanup
            done
            
            git clone https://gitlab.com/1f1e33/android/AnyKernel3.git -b beta
            mv *.cpio AnyKernel3/recovery

            cd AnyKernel3; zip -r1 ${{ env.OFOX_TOP }}/${{ env.COMMIT_ID }}.zip . -x "**.git*" "*placeholder"
        fi

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ env.OFOX_TOP }}/${{ env.COMMIT_ID }}.zip
        name: ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          ## Schrödinger's build
